server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: spring-boot-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/gym?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: ${JWT_EXPIRATION:900000} #15 Minutos
  key: ${JWT_KEY:h2I--1Xw_8ltl_G7lYpCi-$5wRMp8kmky5$Ptm=75lYl150ZVQ6eMCyvrNGkP$UC2CAb-2P3W#zNei8bmj7WMmFuS3KCu0t8kb4GU8LrFLc8rQ-bBcOpxwkNehnIjinTV!slXUfi$dAHZJx!Fv$V2gF$FgiBnx=iS-M!6bLTLiCRgtfkz8!N55vKmr_4bQiK1wMhDIgVzitjXrA2OV8k=DTkyOtbB$MeLnR7N4=ah#!f_XZdkr4QfAt2go537xfHrGuaS55dZUd!6J7#90FPUOpO4F8M6uqzO=Z8NcFhIms5T1KKprcsx$GjhwMI4XZt=3fNqa1=Yu$sgMnjLk7rJdUl}